/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b4b257fb-fa4f-45bd-9ae0-bf0743af5da0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FHcBMjfC6",
    "aws_user_pools_web_client_id": "lc2la0msvfu0jjc474b77c1nj",
    "oauth": {}
};


export default awsmobile;
